### ISSUE TITLE
ÔøΩ >> "

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/odia-mabhabharata#3]
I'm pretty sure that this means double quotation mark ("), though at present it is hard for me to match the occurrences with specific pages in the printed edition so it's hard to confirm. See #2.

**Comment by arlogriffiths** [comment]
once this has been dealt with, the relevant phrase in the README can be rewritten.

**Comment by michaelnmmeyer** [comment]
This is dealt with.
